const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfReviwes: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirt',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Addidas',
      rating: 3.5,
      numOfReviwes: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirt',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 3.2,
      numOfReviwes: 6,
      countInStock: 30,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.5,
      numOfReviwes: 13,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 100,
      brand: 'ZARA',
      rating: 3.9,
      numOfReviwes: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 84,
      brand: 'American Eagle',
      rating: 2.4,
      numOfReviwes: 8,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;